pages:
  image: node:12.13.1
  only:
    - master
  artifacts:
    paths:
      - public
  script:
    - npm install
    - npm run build
    - npm run export
    - rm -rf ./public
    - mv ./out ./public
