config:
    author: han4wluc
    siteName: han4wluc's homepage
    siteDescription: han4wluc is a freelance fullstack developer
    defaultPageTitle: han4wluc's homepage
    blogTitle: Blog
    baseUrl: han4wluc.gitlab.io

    # For Twitter cards, this logo must be a hosted url, not a relative path.
    # Must be square. Minimum size is 144x144; maximum size 4096x4096.
    websiteLogo: "https://han4wluc.gitlab.io/static/images/profile.jpg"

    # if your string begins with a special character, you usually have to put it in quotes
    twitterHandle: "@han4wluc"
    twitterCardType: summary

    # This is list is used to create the links in the navigation panel
    navigation:
        - { text: Home, link: / }
        - { text: Blog, link: /blog }
        - { text: About, link: /about }

    css:
        primaryColor: "#536DFE"
        accentColor: "#455A64"
        lightGray: "#eeeeee"
        backgroundColor: "#ffffff"
        black: "#333"
